import {
  githubIcon,
  telegramIcon,
  linkedinIcon,
  instagramIcon,
  twitchIcon,
  tiktokIcon,
  frontendmastersIcon,
  codecademyIcon,
  nglIcon,
  dailyDevIcon,
  codewarsIcon,
  whatsappIcon,
} from "../imgs/icons";
export let myObj = [
  {
    id: 0,
    name: "github",
    url: "https://github.com/moonhuntercode",
    path: `${githubIcon}`,
  },

  {
    id: 1,
    name: "instagram",
    url: "https://www.instagram.com/victorcode_/",
    path: `${instagramIcon}`,
  },
  {
    id: 2,
    name: "codecademy",
    url: "https://www.codecademy.com/profiles/victor.code",
    path: `${codecademyIcon}`,
  },
  {
    id: 3,
    name: "pregunta anónima",
    url: "https://ngl.link/victor.code",
    path: `${nglIcon}`,
  },
  {
    id: 4,
    name: "dayli.dev Profile",
    url: "https://app.daily.dev/moonhunter_code",
    path: `${dailyDevIcon}`,
  },
  {
    id: 5,
    name: "linkedin",
    url: "https://www.linkedin.com/in/victorcode/",
    path: `${linkedinIcon}`,
  },
  {
    id: 6,
    name: "frontendmasters",
    url: "https://frontendmasters.com/u/victorcode/",
    path: `${frontendmastersIcon}`,
  },
  {
    id: 7,
    name: "twitch",
    url: "https://www.twitch.tv/victorcode_",
    path: `${twitchIcon}`,
  },
  {
    id: 8,
    name: "codewarrior",
    url: "https://www.codewars.com/users/victor.code",
    path: `${codewarsIcon}`,
  },
  {
    id: 9,
    name: "old portfolio",
    url: "https://victor-code.vercel.app/",
    path: `/software-icon-2.svg`,
  },
  {
    id: 10,
    name: "tiktok",
    url: "https://www.tiktok.com/@victorcode_",
    path: `${tiktokIcon}`,
  },
  {
    id: 11,
    name: "telegram C++/C",
    url: "https://t.me/Cpluspluslatino",
    path: `${telegramIcon}`,
  },
  {
    id: 12,
    name: "whatsapp community",
    url: "https://chat.whatsapp.com/DywYPe8kXCTCrxvlvqMg2S",
    path: `${whatsappIcon}`,
  },
  {
    id: 13,
    name: "whatsapp channel",
    url: "https://whatsapp.com/channel/0029Va9E7ck0G0XjYd4zgF1G",
    path: `${whatsappIcon}`,
  },
];
